language: node_js
cache:
  - yarn
node_js:
  - '8.11'
jobs:
  include:
    - stage: tests
      name: "Linter"
      script: yarn run lint

    - stage: tests
      name: "Unit tests"
      script: yarn run test-ci

    - stage: tests
      name: "Solidity Coverage"
      script:
        - yarn add codecov solidity-coverage
        - yarn coverage
        - codecov -f coverage/lcov.info
